version: '3'
services:
  postgres:
    container_name: postgres
    restart: always
    build:
      context: ./postgres
      dockerfile: Dockerfile
    ports:
      - 5432:5432
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
  bo:
    container_name: back-office
    restart: always
    build:
      context: ./bo
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - postgres